const contextData = {
    words: [
        "APPLE",
        "BALL",
        "CAT",
        "DOG",
        "ELEPHANT",
        "FISH",
        "GOAT",
        "HOUSE",
        "INDIA",
        "JAGUAR",
        "KITE",
        "LION",
        "MANGO",
        "NEST",
        "OWL",
        "PARROT",
        "QUEEN",
        "RABBIT",
        "SUN",
        "TRAIN",
        "UMBRELLA",
        "VAN",
        "WATCH",
        "XYLOPHONE",
        "YAK",
        "ZEBRA",
    ],
    keyCommands: {
        r: "reset",
        h: "help",
        n: "numbers",
        a: "abcs",
        " ": "exec",
        Enter: "exec",
    },
};
